### ISSUE TITLE
braid-rewind.slang broken

### ISSUE THREAD

**Issue by LazyBumHorse** [libretro/slang-shaders#102]
There's a simple syntax error in braid-rewind.slang:
> [ERROR] ERROR: braid-rewind.slang:19: '' :  syntax error, unexpected RIGHT_BRACE, expecting COMMA or SEMICOLON

So it should be:
```
layout(std140, set = 0, binding = 0) uniform UBO
{
    mat4 MVP;
    vec4 OutputSize;
    vec4 OriginalSize;
    vec4 SourceSize;
    float FrameDirection; <---
} global;
```

after fixing that there's another vague error:
> [ERROR] [slang]: Unknown semantic found.
> [ERROR] [slang]: Failed to reflect SPIR-V. Resource usage is inconsistent with expectations.

The GLSL version of the shader works like it should (at least in cores with proper rewind).

**Comment by hizzlekizzle** [comment]
I'll just nuke that shader, since slang doesn't even have framedirection. I had initially ported it thinking we would add it at some point, but we never did.

**Comment by LazyBumHorse** [comment]
I just implemented the FrameDirection semantic and added support for glcore and vulkan, because I wanted to try building RetroArch anyways.
And it works!
I'm not yet ready to create a pull request though, because I'm not sure exactly if it's fine to push `int32_t`s, tell Slang it's an `SPIRType::Int` and be done with it.
One possible issue is that `int32_t` isn't necessarily platform-independent, contrary to `uint32_t` there are multiple possible implementations and RetroArch targets basically all platforms...
Need to think about this one, so don't nuke the shader yet!

**Comment by hizzlekizzle** [comment]
oh, well, I already did it, but I can bring it back lol

That's awesome that you're adding it. I always liked the braid-rewind shader and have wanted to improve it some but just never had much reason to do it, since the semantic didn't exist... I'll be able to bring over the VHS shader's rewinding effect, too, w00t

**Comment by LazyBumHorse** [comment]
The patch should now be [online](https://buildbot.libretro.com/nightly/).

**Comment by hizzlekizzle** [comment]
sounds good. I'll get that shader updated ASAP. Thanks!
