### ISSUE TITLE
several shaders show artifacts in glcore

### ISSUE THREAD

**Issue by LazyBumHorse** [libretro/slang-shaders#103]
I'm actually not sure if this is a shader problem or a RetroArch video driver (i.e. Slang shader translation) problem, but here's what's happening:

Using the glcore video driver, `xbr-mlv4-multipass` shows artifacts:
![glcore xbr-mlv4-multipass glslp](https://user-images.githubusercontent.com/31176526/58326633-aea22200-7e2d-11e9-9b50-b1b2fa0f5c73.png)
It's fine in Vulkan:
![vulkan xbr-mlv4-multipass glslp](https://user-images.githubusercontent.com/31176526/58326726-f9bc3500-7e2d-11e9-9071-2af3bcff5c57.png)
Here's glcore again:
![glcore xbr-mlv4-multipass slangp](https://user-images.githubusercontent.com/31176526/58326776-19ebf400-7e2e-11e9-9e54-6248a5dc196f.png)
And here's the GLSL version in gl for another comparison:
![gl xbr-mlv4-multipass glslp](https://user-images.githubusercontent.com/31176526/58326768-15bfd680-7e2e-11e9-994c-e33f29043f50.png)

I'm using a GTX 1060 6GB.

This may be related to #70 as well, though Vulkan is innocent this time.

**Comment by hizzlekizzle** [comment]
Looks like a glslang issue. Other reflections seem to be okay.

**Comment by LazyBumHorse** [comment]
Now that I know what to look for, I found several shaders that seem to be affected by this as well:
- `xbr-lv3-multipass`
- All `hqx` shaders
- `aa-shader-4.0` (and probably `-level2`)
- `scalefx` has stray pixels similar to `xbr-lv3-multipass`

Can we break it down what they have in common?
Maybe there's already an issue in the [glslang's issue tracker](https://github.com/KhronosGroup/glslang/issues).

**Comment by hizzlekizzle** [comment]
I'm not getting any issues with xbr-mlv4-multipass, scalefx or hqx, but I am getting rough edges on xbr-lv3-multipass. Using glcore with mesa driver on a Haswell integrated GPU.

**Comment by LazyBumHorse** [comment]
Do you mean this when you say rough edges in `xbr-lv3-multipass`?
![xbr-lv3-multipass slangp](https://user-images.githubusercontent.com/31176526/58382915-89014e00-7fd0-11e9-9652-b3587964b559.png)
Noticeable at the font the most, I don't seem to get issues with the single pass `xbr-lv3` version:
![xbr-lv3 slangp](https://user-images.githubusercontent.com/31176526/58382926-acc49400-7fd0-11e9-9e7b-1a9907c348da.png)

And are you sure you don't have any issues with the other examples? They aren't very pronounced for me but in direct screenshot comparison to glsl it becomes very obvious something is wrong, e.g. at first glance `hq2x` looks okay until you notice the 'ghosting' of the font and then the fact it doesn't smooth the pixels at all:
![hq2x slangp](https://user-images.githubusercontent.com/31176526/58382833-6ae71e00-7fcf-11e9-82a4-08e1533e8096.png)
vs glsl
![hq2x glsl](https://user-images.githubusercontent.com/31176526/58383052-404a9480-7fd2-11e9-8281-f66ad14c5c1c.png)



`scalefx` is also very very subtle, here's another (upscaled) comparison, slang in glcore vs glsl in gl:
![scalefx slangp](https://user-images.githubusercontent.com/31176526/58383021-dfbb5780-7fd1-11e9-9ee9-328d84fbec62.png)
Notice e.g. the darker lines between the gray bricks besides the king.
vs glsl:
![scalefx glsl](https://user-images.githubusercontent.com/31176526/58383011-ada9f580-7fd1-11e9-859b-bcb39df8f7c7.jpg)

I want to try debugging it myself, but I don't even know how Slang or `glslang` you mentioned work, neither what reflections precisely are.

**Comment by hizzlekizzle** [comment]
Here's what lv3-multipass looks like for me:
![Screenshot from 2019-05-26 20-24-43](https://user-images.githubusercontent.com/2805586/58389992-73058480-7ff4-11e9-9a35-97bbae9ced90.png)
hq4x looks okay here:
![Screenshot from 2019-05-26 20-26-35](https://user-images.githubusercontent.com/2805586/58390023-9b8d7e80-7ff4-11e9-8f7d-bc6b75799420.png)
The way slang works is it gets converted to SPIR-V, which then gets "reflected" back to whatever driver's native code via glslang. So, there are several places where inconsistency can sneak in, whether it's the normal endpoint driver issues we always have to deal with when shaders are involved, but also issues with glslang's reflection (rare, but it can happen).

**Comment by LazyBumHorse** [comment]
I think I found the issue!
It was my graphics driver settings all along. I forced 16x anisotropic filtering in all programs, which surprisingly messes up the shaders in glcore.
Now all the named shaders behave like they should.

Well, _almost_.
`aa-shader-4.0` and `xbr-lv4-multipass` still show some line artifacts.
`aa-shader-4.0` shows a rough line every 32 pixels (at least in the bottom half):
![aa-shader-4 0](https://user-images.githubusercontent.com/31176526/58468241-7b1d0b80-813d-11e9-8adb-d0a619816acf.png)
`xbr-lv4-multipass` has seemingly a single rough line going through the bottom characters:
![xbr-lv4-multipass](https://user-images.githubusercontent.com/31176526/58468243-7bb5a200-813d-11e9-8d37-d7d14d8dec4e.png)

**Comment by LazyBumHorse** [comment]
I found the `xbr-lv4-multipass` issue so weird so I did some more testing.
It appears to really be only one singular line artifact and it does appear in Snes9x glcore and vulkan (didn't know you could use vulkan with it, but apparently you can).
I also couldn't replicate the issue in cores for other systems and I believe that is because of differing vertical resolutions.
In higan you can set different internal resolutions and only if the vertical resolution is 224 (like in Snes9x), the single rough line appears.
Maybe some kind of precision error? Rounding error? Off-by-one error?
Compared to glsl, the 'slicing' appears to be different, you see what I mean when you switch between the images:
![slang](https://user-images.githubusercontent.com/31176526/58473566-313a2280-8149-11e9-8958-de81fea41dca.png)
glsl:
![glsl](https://user-images.githubusercontent.com/31176526/58473567-31d2b900-8149-11e9-98ef-75935da7f156.png)
I should have activated integer scale...
![gl aa 4x](https://user-images.githubusercontent.com/31176526/58481193-2dfc6200-815c-11e9-900e-d9f15de01e58.png)
![glcore aa 4x](https://user-images.githubusercontent.com/31176526/58481197-2dfc6200-815c-11e9-8047-1913ed214815.png)
Interestingly the artifact disappears when integer scaling, the horizontal 'slicing' still seems to be different though, which is weird - different rounding?

So a workaround would be to set the scaling of the last pass to a clean 4x or 5x instead of 'Don't care'.

---

The `aa-shader-4.0` issue appears in glcore and vulkan and also seems to be dependent on the vertical resolution. 224 and 240 have issues, but 448 and 480 appear fine. Some other cores/resolution I tested appeared fine as well.

I thought this had something to do with the use of `scale_type(...) = "viewport"` and nearest neighbor scaling because 224 and 240 don't divide 1080 (and maybe the issue is just slightly hidden with 448 and 480), but using integer scale or setting `scale_type` to `source` and `scale` to 4x, the lines are still there.

Looking closer:
![glcore aa 4](https://user-images.githubusercontent.com/31176526/58479358-6dc14a80-8158-11e9-88c8-f9ebaf253cb2.png)
glsl:
![gl aa 4](https://user-images.githubusercontent.com/31176526/58479360-6e59e100-8158-11e9-838c-dcceadad5307.png)
This looks like an off-by-one error, all lines appear to shift down by 1 in Slang, except for every 32th (in 1080p) or 28th (with integer scaling, 896'p') line.

**Comment by hizzlekizzle** [comment]
yeah, rounding errors like that are very common. I usually deal with them by multiplying the texcoord calculation in the vertex by something like 1.0001 but I believe the issue is also GPU-dependent, so sometimes 1.0001 does it, other times I have to go up to 1.0004 or somesuch.

**Comment by LazyBumHorse** [comment]
Hm... that sucks.
I guess you just can't expect pixel perfect output in every case, but I didn't think it would be that bad.

What's just so weird to me is that the code for the `aa-shader-4.0` slang and glsl shaders are actually identical, except glsl is using precision qualifiers for OpenGL ES, which I'm not using, so...

Oh well, the original problem has been solved, `xbr-lv4-multipass` has a workaround and `aa-shader-4.0` seems to only break in that particular resolution on my particular system in this particular universe, so the topic can be closed.

**Comment by hizzlekizzle** [comment]
I spotted another common culprit for rounding errors in aa-shader-4.0: floor(). Adding a small offset to it appears to have cleaned it up quite a bit!
https://github.com/libretro/slang-shaders/commit/79c95a5036af4a38138dc8f924445a168eee4e54

**Comment by LazyBumHorse** [comment]
That works very well! The difference image is almost completely black.
Only around the very top, there's still one line artifact, probably because the effect of the multiplication is too low at that point.

![glcore](https://user-images.githubusercontent.com/31176526/58493245-cbfb2700-8172-11e9-860f-a8ecf1d79f72.png)
How it should look like:
![gl](https://user-images.githubusercontent.com/31176526/58493243-cb629080-8172-11e9-8d0c-f53b4c67a4ec.png)
