### ISSUE TITLE
CRT-Royale Geometry Modes

### ISSUE THREAD

**Issue by Ebsy** [libretro/slang-shaders#106]
Hi,

I posted in https://github.com/libretro/glsl-shaders/issues/40 recently with @hizzlekizzle and thought I should open a new issue after moving to the vulkan driver/slang shaders exclusively.

Setting the geometry parameter in CRT-Royale will mostly show a black screen. After some tweaking with the parameters an image is displayed but it's clearly the wrong image. It looks like there's some issue with crt-royale-geometry-aa-last-pass.

Setting geometry to 0 shows the following (correct) image
![Screenshot_5](https://user-images.githubusercontent.com/2177816/58830470-abd3d800-864a-11e9-8d76-df4ce8632fc0.png)

Setting geometry to 3 and tweaking the parameters to 'extreme' values will give a reversed image, yet it's somehow still 'cylindrical' due to the geom 3 setting.
![Screenshot_6](https://user-images.githubusercontent.com/2177816/58830549-da51b300-864a-11e9-9407-c318159d3445.png)

(note: radius, tilt angle x and view distance)

I've had a quick look at the crt-royale-geometry-aa-last-pass files but I'm a bit lost if anyone has any pointers of where to look I'll gladly help out by experimenting with the values.

**Comment by hizzlekizzle** [comment]
I spoke with trogglemonkey briefly about this a few weeks ago and he said he'd try to take a look at it. He's been busy, though, apparently, so there's no ETA.

**Comment by ibm2431** [comment]
Apologies if this is a second email notification, but I managed to get CRT-Royale to display a curved _not mirrored_ image today.

But instead of making a new comment, I had instead edited my initial comment from two days ago - and I don't think notifications go out on those. So here's a ping~!

**Comment by hizzlekizzle** [comment]
Hey, the geom modes should be fixed now.

After reading your post, I spent a whole day troubleshooting GLSL and Cg/HLSL differences in matrix ordering, component-wise multiplication and UV orientation, but in the end it all came down to a mistake I made a long time ago with converting Cg/HLSL's atan2 to GLSL's atan. -_-

I'll try to update the glsl shader version soon, too.
