### ISSUE TITLE
Rename "retro" Dir To "interpolation", Move retro-v2 and bevel to Handheld

### ISSUE THREAD

**Issue by Awakened0** [libretro/slang-shaders#108]
Brought this up on Discord, figured I'd make an issue so it's not forgotten.

"I was thinking, due to Digital Foundry and MLIG videos, hopefully more people know what interpolation is. Maybe the "retro" shader dir should be renamed to "interpolation"? I think the only two shaders in there that aren't interpolation shaders are bevel and retro-v2. Moving those to handheld could work, since they're grid shaders that kind of give an LCD effect."

Same would apply to the other shader repos.

**Comment by hizzlekizzle** [comment]
Alright, this should be done now. Would you mind checking my work and make sure I didn't miss anything?

**Comment by Awakened0** [comment]
The ascii shader should be moved somewhere else; maybe misc. Looks good besides that; of course there're the glsl and common shaders repos to mirror these changes to as well when you get a chance. I didn't realize there were so many presets that use these shaders that had to be updated too >_<

**Comment by Awakened0** [comment]
Looked over your changes to the other repos. glsl looks good. Common shaders has bead in interpolation now, which should go to misc. And move 5xbr-retro to xbr.

It's been so long since I've used cg shaders that I forgot about bead. That's kind of a fun one that would be cool to have in slang someday.

**Comment by hizzlekizzle** [comment]
Awesome. I think we're all set here (and I ported bead for you while I was at it).

I'll go ahead and close this, but if you find any remaining stragglers, just let me know.

**Comment by Awakened0** [comment]
Thanks :)
