### ISSUE TITLE
Converting warp cg shaders

### ISSUE THREAD

**Issue by Papermanzero** [libretro/slang-shaders#109]
Those shaders are missing
https://github.com/libretro/common-shaders/tree/master/warp/shaders

**Comment by hizzlekizzle** [comment]
Yeah, I never converted them because they're not used by m/any presets and I didn't think anyone really used them.

**Comment by Papermanzero** [comment]
I did at least the dilation filter is sometime useful. Only the strenght of the shader needs to be adjustable

**Comment by hizzlekizzle** [comment]
alright, I added warp, erosion and smart-morph

**Comment by Papermanzero** [comment]
Thank u
