### ISSUE TITLE
Add "Linear Gamma Weight" Option to bandlimit-pixel

### ISSUE THREAD

**Issue by Awakened0** [libretro/slang-shaders#117]
I mentioned the differences I observed between pixellate and bandlimit-pixel to ResetEra user Pargon and he replied with an [interesting post](https://www.resetera.com/threads/john-linnemans-doom-patch-video-thoughts-about-resizing-and-uneven-pixels.165084/#post-28324277). From what they're saying, a similar option to pixellate's "Linear Gamma Weight" could improve source image accuracy.

**Comment by hizzlekizzle** [comment]
bandlimit-pixel should already be operating in linear gamma: https://github.com/libretro/slang-shaders/blob/master/interpolation/bandlimit-pixel.slangp#L2

**Comment by Awakened0** [comment]
Ah, thanks for the clarification. I've passed that info over to that thread.
