### ISSUE TITLE
crt-guest-dr-venom glow emulation not scaling properly

### ISSUE THREAD

**Issue by strawbrains** [libretro/slang-shaders#132]
When using an ntsc shader in the chain or built into the core (like mesen for example) the glow seems to cut off too soon horizontally.  I've noticed similiar behavior when the content is 480i as well.  I can adjust for it to compensate in the shader glow settings, but it would be nice to not have to do that, similar to how crt-royale works.  As an example, if you use an ntsc shader with royale, the glow effect applies evenly by default.

**Comment by hizzlekizzle** [comment]
Hmm, can you post a screenshot? it seems to work okay here:
![Screenshot from 2020-03-15 10-25-39](https://user-images.githubusercontent.com/2805586/76704553-ccd05b80-66a7-11ea-8ed0-71f5f2204e01.png)

**Comment by strawbrains** [comment]
Here is the default settings, with the glow cranked up to max for the demonstration.

![240pSuite-200315-171615](https://user-images.githubusercontent.com/12358227/76710851-27d27480-66e1-11ea-98d6-751fafa44de8.png)

Here is the default settings, but using the ntsc 256px preset, with the glow cranked up to max..
You can see around the right and left edges of the bars where the glow cuts off.

![240pSuite-200315-171707](https://user-images.githubusercontent.com/12358227/76710858-391b8100-66e1-11ea-8065-61a9f771cd5b.png)

For a comparison, here is how the royale shader handles it.  This is the royale 256px composite preset with the diffusion cranked up.

![240pSuite-200315-172350](https://user-images.githubusercontent.com/12358227/76710917-c232b800-66e1-11ea-8f7a-ba21e92afe5c.png)

Here is a mark up to point it out.  

![240pSuite-200315-171707](https://user-images.githubusercontent.com/12358227/76711105-78e36800-66e3-11ea-8786-bf17c972d5fa.png)

**Comment by guestrr** [comment]
Due to the nature of the preset the horizontal pixels get 2x smaller relatively at this stage and this also affects horizontal glow width.

The solution is to increase the horizontal glow radius.

**Comment by strawbrains** [comment]
ok thanks, I'll just do that then for now.  I'm not sure what the royale shader does to mitigate it, but I can live with having a few presets with a few different parameters.  Love the shader and keep up the good work.
