### ISSUE TITLE
'misc/interlacing' should use OriginalSize, not SourceSize

### ISSUE THREAD

**Issue by anikom15** [libretro/slang-shaders#161]
If _misc/interlacing_ is used after some shader that requires scaling, SourceSize will no longer equal OriginalSize. The shader depends on accurate information on the size of the emulated device's video output to perform its function. I fail to see how SourceSize can make any sense when OriginalSize exists.

If backwards compatibility is absolutely necessary, a parameter should be added to allow for the shader to use OriginalSize.

**Comment by hizzlekizzle** [comment]
Hmm, I seem to recall doing this at some point and then changing it for some reason, but I can't think of what that reason would be (it's been several years), so yeah, I'm okay with it.

**Comment by anikom15** [comment]
FWIW I created a new shader with OriginalSize instead of SourceSize and haven't run into any issues.

**Comment by twinaphex** [comment]
Hi, any idea here on how to move forward?

**Comment by hizzlekizzle** [comment]
Looks like it was already done the next day: https://github.com/libretro/slang-shaders/commit/9e9804c42853bb7cf82aab95d54ab44997e684b9 and we just never closed the issue. Doing it now.
