### ISSUE TITLE
CRT-Pi looks wrong in Slang with D3D driver (and correct when is GLSL with OpenGL)

### ISSUE THREAD

**Issue by matheuswillder** [libretro/slang-shaders#186]
As the title says. Using the D3D driver and Slang CRT-Pi shader, the image looks pixelated and incorrect, but it runs fine when under the OpenGL driver. I tried to make a screenshot, but even it turns out incorrect (screenshot turns green ?!) using D3D and it's done correctly in OpenGL. The screenshot is below, first the D3D version and then OpenGL..

I would appreciate it if it could be fixed, CRT-Pi seems to be the only curvature shader that run without slowing my potato (Second Generation Intel Core with integrated graphics), and it works best with the D3D drivers on Windows.

![Donkey Kong Country-210809-231118](https://user-images.githubusercontent.com/46294160/128800765-8d1e7def-d310-4f49-ab74-27d7004a3db0.png)
![Donkey Kong Country-210809-231330](https://user-images.githubusercontent.com/46294160/128800774-99a621c3-7e3b-4c69-a2c0-440ac436cc71.png)

**Comment by hizzlekizzle** [comment]
Looks fine here with d3d10/11/12. It sounds like it's probably a driver issue rather than a slang shader issue.

**Comment by matheuswillder** [comment]
Ok it must be a driver issue, I decided to ask because all the others look correct in D3D (CRT-Hyllian, even CRT-Royale), they just run very slow. Thank you for the answer. Should I close this issue?

**Comment by hizzlekizzle** [comment]
Sure. It is good information, but probably not something we can fix, unfortunately.

**Comment by matheuswillder** [comment]
Okay, thank you so much for the work of everyone on the team to keep everything operating correctly and getting better every day. I will close this issue now.

**Comment by matheuswillder** [comment]
@hizzlekizzle Just to clarify some information here, below is a screenshot of Slang CRT-Pi shader with D3D (and the problem I tried to show before) and then a screenshot of GLSL CRT-Pi shader with OpenGL and without the problem. I have set **Mask brightness** to **0.00** on both of them to make the problem more evident, see the artifacts that appear in the sky:

![slang](https://user-images.githubusercontent.com/46294160/132151298-56632d89-fcde-40f3-8531-13c9fd7fbfb2.png)
![glsl](https://user-images.githubusercontent.com/46294160/132151308-4ccb4b80-f6cf-4a91-afc6-111fe5290bad.png)

Another screenshot in Slang also with the problem (with **Mask brightness** to **0.00** and **Scanline weight** at **15.00** to make the problem more evident):

![lionkingslang](https://user-images.githubusercontent.com/46294160/132154290-c1496e00-8604-4ae8-94b7-a1d8816255da.png)

This seems to happen even with the default parameters, just is hard to see. I hadn't noticed before that curvature wasn't being applied in the GLSL version, I suffer from low visual acuity due to genetic reasons so it's a little difficult to notice some things. Set **Screen curvature - vertical** at **0.00** corrects the problem.

Also, in Slang version the game always looks pixelated, this seems to be because **filter_linear0** is turned to **false** in **crt-pi.slangp**.

Well, sorry if I ended up creating some confusion with the information I sent before, due to my health problem I can't see things accurately and I always have doubts if it's me or if it's really a problem. I'll keep this issue closed as I'm not sure if it's due to my computer's drivers, but I would appreciate it if anyone can test it out.

**Comment by hizzlekizzle** [comment]
No problem.

The artifact you see is called "moire" and it happens in varying degrees any time you have scanlines with curvature. It's caused by aliasing, which you can mitigate with low-pass filtering (that is, blurring).

Am I correct in thinking that setting the slang version to linear filtering reduces the moire/aliasing to be similar to the GLSL version?

**Comment by matheuswillder** [comment]
Thanks for the answer and for explaining.

I can't see any difference in moire when setting the linear filtering on or off, but due to my health issue I am not sure.

However, using the linear filtering makes the Shader look better and similar to the GLSL version. Linear filtering is set to false in crt-pi.slangp and true in crt-pi.glslp, which was one of the reasons I originally thought the Slang version was not working correctly in D3D, in addition to the moire effect that I had never heard of before.

But as you said in the first answer it's not really a problem with the Slang, so again I appreciate the answers and help.

I just leave the suggestion that maybe the linear filtering should be set to true in the Slang version as it already is in the GLSL version, the visual result looks better and more accurate for what CRT monitors were like.
