### ISSUE TITLE
[Question] Can i somehow apply these shaders to arbitrary image?

### ISSUE THREAD

**Issue by axredneck** [libretro/slang-shaders#251]
I make pixel art, and i want to give it "retro" look using some analog/NTSC/composite shaders.

**Comment by hizzlekizzle** [comment]
The easiest thing to do is load an image with the built-in image-viewer core and apply the shader(s) that way, then take a screenshot of the resulting image.

But to directly answer your question: not that I know of.

**Comment by axredneck** [comment]
> ... load an image with the built-in image-viewer core ...

Can't figure out how to do this sadly. Can somebody help me?

**Comment by hizzlekizzle** [comment]
What kind of image file are you trying to open? It just opens them directly here without asking for a core.

**Comment by axredneck** [comment]
Png

**Comment by hizzlekizzle** [comment]
Try loading it through the "big picture" interface's "load content" entry.

**Comment by mudlord** [comment]
Sounds like a tool needs to be written for applying/previewing shaders in the RA ecosystem and saving to optimized image files. Gives me something to think about as a potential proj, at least.

**Comment by axredneck** [comment]
> Try loading it through the "big picture" interface's "load content" entry.

Thank you, it works! (I wonder why it doesn't work from WIMP...)
