### ISSUE TITLE
[Request] Port fake-CRT-Geom Shader family to Slang

### ISSUE THREAD

**Issue by matheuswillder** [libretro/slang-shaders#253]
Port fake-CRT-Geom Shader family (**fake-CRT-Geom.glsl** and **fake-CRT-Geom-potato.glsl**) from GLSL to Slang, so it can be usable on D3D10/11 or Vulkan driver.

**Comment by metallic77** [comment]
Fake-crt-geom ported. Later I will port fake-crt-geom-potato too.

**Comment by metallic77** [comment]
It uses sharp filter from crt-pi by default, and crt-geom mask. Curvature and scanlines from fake lottes.

**Comment by metallic77** [comment]
Added a "speed-up" option to fake-crt-geom to work as in fake-crt-potato (it's a bit heavier). If that covers you, maybe you can close the issue.

**Comment by metallic77** [comment]
Load fake-crt-geom, change linear to nearest. Then add another pass, stock.slang and filter linear. Didn't try, just saying.

**Comment by metallic77** [comment]
Anyway i just ported potato too.
