### ISSUE TITLE
[Regression] Bob-Deinterlacing broken at x1 scale

### ISSUE THREAD

**Issue by ichee** [libretro/slang-shaders#255]
The Bob-Deinterlacer appears to be offset, creating cut-off text and over-blurred images on some screens. Also affects screens that are not interlaced.

interlaced screen (text and edges of the diamond):
![pic1](https://user-images.githubusercontent.com/22252639/176363470-d96ef997-8d3d-4018-80da-9a97d11b1dd2.png)

progressive screen (the S at the top middle, the l in select and the triangle symbol at the lower left):
![pic2](https://user-images.githubusercontent.com/22252639/176363593-2c740e1d-c5ba-4b78-a096-c64e51ac2c6a.png)

Regressed with commit d0524545351ab18beb48a764547ea828129c2afc.

https://github.com/libretro/slang-shaders/blob/5f45558608ce2a320ec7bb9a8172ddbfbc28aa44/misc/bob-deinterlacing.slang#L57

Changing `0.5` to `1.0` fixes the issue.

Windows 11

Nvidia RTX 3090

**Comment by hizzlekizzle** [comment]
Does it help if you change the 0.5 to 0.49999? GPU-specific rounding issues are very common.

**Comment by ichee** [comment]
No, but `0.51` does.

Odd that a 0.01 increase would have so much of an effect.
