### ISSUE TITLE
scalefx9-aa-blur-hazy shaders cannot be loaded.

### ISSUE THREAD

**Issue by vavelpo** [libretro/slang-shaders#350]
Confirmed on Windows and Android.

File:

- RetroArch\shaders\shaders_slang\presets\scalefx9-aa-blur-hazy-ntsc-sh1nra358.slangp
- RetroArch\shaders\shaders_slang\presets\scalefx9-aa-blur-hazy-vibrance-sh1nra358.slangp

System:

- Windows 10 64bit
- Android 10

RetroArch:

- 1.14.0 64bit

**Comment by hizzlekizzle** [comment]
These presets should be fixed now. It'll take a few hours for them to trickle down to the online updater, but once that happens, you can update the shaders from there.

**Comment by vavelpo** [comment]
I have confirmed that it loads correctly after running the online update.

Thank you very much.
