### ISSUE TITLE
Vertical artifact in crt-consumer shader

### ISSUE THREAD

**Issue by johanbcn** [libretro/slang-shaders#352]
I have tried the new crt-consumer shader and noticed that it displays a permanent vertical line artifact. This doesn't happen on the GLSL version.

GLSL version:
![R4 - Ridge Racer Type 4 (USA)-230120-171213](https://user-images.githubusercontent.com/721143/213750918-402cc47c-57ef-49ee-982d-1cb997755250.png)

SLANG version (see in full resolution):
![R4 - Ridge Racer Type 4 (USA)-230120-171651](https://user-images.githubusercontent.com/721143/213750930-4ec672c1-bbfb-4b34-91bf-d8442f0aecf5.png)

**Comment by hizzlekizzle** [comment]
Seems to fix it if I change this line: https://github.com/libretro/slang-shaders/blob/master/crt/shaders/crt-consumer.slang#L92 to multiply the coord by 1.0001 instead of 1.001. Does that work for you, as well?

**Comment by johanbcn** [comment]
Yes, that fixed it!

Thank you hizzlekizzle.

**Comment by hizzlekizzle** [comment]
Np. I'll make that change in the repo.
