### ISSUE TITLE
Error in crt-lottes

### ISSUE THREAD

**Issue by star69rem** [libretro/slang-shaders#368]
Can this be fixed?

The input stage requires Semantic/Index (TEXTCOORD,1) as input, but it is not provided by the output stage.

https://user-images.githubusercontent.com/1000503/215376730-64bc20f9-90de-4c73-97be-9dba7085d466.png

It's breaking debug mode settings with D3D11.

**Comment by star69rem** [comment]
Just removing the "layout(location = 1) in vec2 FragCoord;" line seems to fix it.

**Comment by hizzlekizzle** [comment]
Hmm, yeah, dunno what that's doing in there in the first place. Wanna PR that fix? if not, I can hop in the web editor and clear it out in a bit.
