### ISSUE TITLE
Presets broken due to wrong texture or include paths 

### ISSUE THREAD

**Issue by chyyran** [libretro/slang-shaders#369]
https://github.com/SnowflakePowered/librashader/blob/master/BROKEN_SHADERS.md

These were found by 
* parsing all shader presets: https://github.com/SnowflakePowered/librashader/blob/master/librashader-presets/tests/parse_all.rs#L5
* preprocessing all referenced shaders in all presets: https://github.com/SnowflakePowered/librashader/blob/master/librashader-preprocess/tests/parse_all.rs#L7

librashader's implementation of the parser/preprocessor is obviously different from RetroArch's implementation but all errors were confirmed to be a result of missing files and not implementation differences in parsing logic. I haven't tested what happens when loading these shaders with RetroArch but if they did load I would guess the output would not be as intended.

**Comment by chyyran** [comment]
If you're interested, [here is a list of hacks](https://github.com/SnowflakePowered/librashader/blob/master/librashader-presets/src/parse/value.rs#L377) I've implemented to account for variations in preset syntax that RetroArch shouldn't properly handle (to the best of my knowledge) at the moment.

**Comment by hizzlekizzle** [comment]
Thanks, I'll take a look.

**Comment by hizzlekizzle** [comment]
I think we're all set here. If not, or if you find any other goodies, we can reopen it. Thanks again :)
