### ISSUE TITLE
Some crt geom presets are now broken

### ISSUE THREAD

**Issue by joepogo** [libretro/slang-shaders#516]
Recently, I updated my slang shaders online and found some of my custom shader presets I had saved are now broken. 

I then tested out the normal crt geom ntsc presets my custom ones are built off and found these shaders now display waaay incorrect colors and other screen glitches:

Crt-geom-deluxe-ntsc-adaptive.slangp - lines all over the screen and incorrect colors.

Crt-geom-ntsc-conposite-sharp-tate is now blurry and smeared.  

Crt-geom-ntsc-upscale-sharp-tate - extremely blurry

The other crt geom ntsc presets are ok. Did something get broken with these recently?

Reverting back to an older shaders_slang folder those presets work correctly again. 

Doesn't matter what core or game you try. 😔

I can definitely tell something changed as some of the options are different now as well on those listed above.

EDIT** just went back and looked. Yep, something changed 4 days ago with crt geom deluxe adaptive preset in the repository which is what I have a custom preset saved off of. 

Looks like it's linked with guests shaders but something is off. You can't even select rf in the options for the shader.

**Comment by hizzlekizzle** [comment]
I didn't touch the 'sharp' presets or the files they reference, so they should be okay. The geom-deluxe preset is borked here, too, so I probably need to update the phosphor persistence / feedback reference to reflect having additional passes in front.

**Comment by joepogo** [comment]
Thanks hizzlekizzle, I'll keep an eye out. In the meantime I'll use the older geom adaptive.  😀

Are there much changes or any new benefits to the changes made in the new crt geom adaptive shader out of curiosity?

**Comment by joepogo** [comment]
Hey hizzlekizzle, just checking in, any luck in fixing these?

I noticed today that in guests ntsc shaders you can no longer select rf, is that intentional? You can only select composite, even though rf is in the options.

**Comment by hizzlekizzle** [comment]
Yeah, it looks like he doesn't have the quality presets hooked up at all and just forgot to remove the setting for it.

**Comment by joepogo** [comment]
Hey hizzlekizzle, just checking in. 

Any luck fixing the crt geom presets? I'm holding off updating my slang shaders until these gems work. 

Anyways, hope you're doing well and happy new year! 👊😁

**Comment by hizzlekizzle** [comment]
No, I just reverted it to the old preset. I was never able to get the phosphor trails to work like they should.
