### ISSUE TITLE
Add a few shaders

### ISSUE THREAD

**Issue by wingedonezero** [libretro/slang-shaders#52]
Can you add xbr lvl2 3d the multi pass and single pass ones?

**Comment by hizzlekizzle** [comment]
I just ported a bunch of super-xbr 3D shaders but I'm having trouble porting the lv2-3d ones because they use some Cg-specific boolean comparison construction.

**Comment by wingedonezero** [comment]
No rush i only recently realized i needed the slang shaders for psx hw vulkan. I spent a couple days thinking i did something wrong trying to use glsl lol.

**Comment by hizzlekizzle** [comment]
I'm probably not going to be able to port the lv2-3d versions, but try out those new super-3d ones. Hopefully, they'll get you fixed up :)

**Comment by wingedonezero** [comment]
The super ones are pretty bad lol. Maybe its because they are multi pass could you maybe try to make a single pass of the super 3d one? Idk if its because of that or not but i attached the results of the super 3d ones below. Its only one but they all look about the same. Im using the mednafen hw core in vulkan at 1x native gpu resolution and 1080p. Now i will say if i bump it up to 4x gpu resolution it looks good with out shader but with shader enabled it degrades similar to the picture below. Maybe the super is better for 2d games.

![super xbr test](https://cloud.githubusercontent.com/assets/15163316/24822623/8d6027d6-1bc4-11e7-9704-3e65427b4ee5.png)

**Comment by hizzlekizzle** [comment]
They only work at the scale factor they're designed for. The 2x ones require 2x internal res and the 4x ones require 4x internal res. The 'deposterize' one looks weird most of the time, but the Cg one looks the same, so I assume it's working as intended...

**Comment by wingedonezero** [comment]
Seems to act differently on different games looks fine on dead or alive but not my original test game parasite eve. Upping the internal resolution helped like you mentioned. Ill have to play with it some more maybe having the texture filter on other settings helps as well. I wish there was a off for that when using shaders.
