### ISSUE TITLE
res-independent-scanlines not working with GLCore and D3D

### ISSUE THREAD

**Issue by Jamirus238** [libretro/slang-shaders#542]
With GL and Vulkan it seems to work correctly, but with GLCore and D3D I've encountered the following with both Intel and Nvidia setups:

GLCore: Shader loads, but doesn't apply scanlines. Unless you activate "Automatic Scale", but the "simulated image height" parameter doesn't work.

D3D: shader fails to load.
In the log appear the following error messages:
[ERROR] [slang]: Unknown semantic found.
[ERROR] [slang]: Failed to reflect SPIR-V. Resource usage is inconsistent with expectations.

**Comment by hizzlekizzle** [comment]
ah, this was a funny one to debug.

The imageSize parameter was getting mis-detected as a built-in uniform (that is, the dimensions of an image/framebuffer named 'image'), and this was causing d3d drivers to fail to compile altogether and glcore was giving back a 0/undefined value.

Just changing the name to something else got it going everywhere (AFAICT).

Thanks for the report!
