### ISSUE TITLE
Handheld Gameboy Border shader issue

### ISSUE THREAD

**Issue by Sdancerhj12** [libretro/slang-shaders#574]
This happened to me recently on the SteamDeck after updating and resetting configurations via EmuDeck. Gameplay is way too zoomed in but it’s only with these handheld border shaders. Any other shaders that use auto-scaling like Mega Bezels display fine. 
![most_recent (1)](https://github.com/libretro/slang-shaders/assets/166668804/6c6a597a-69db-464f-97aa-6ca39e628102)

**Comment by hizzlekizzle** [comment]
Looks to me like it's getting a 4x prescale from somewhere. Maybe a video filter is enabled in an override?

**Comment by Sdancerhj12** [comment]
> Looks to me like it's getting a 4x prescale from somewhere. Maybe a video filter is enabled in an override?

Thanks! The 4x prescale gave me a clue and I noticed under Video Filter it was set to Normal4x.filt
Disabled it and everything went back to normal. Not sure if it’s EmuDeck that sets this by default when resetting config.

**Comment by hizzlekizzle** [comment]
eyyy, nice. If you're all set, I'm gonna close this one out.
