### ISSUE TITLE
mudlord-pal-vhs.slangp failed to apply

### ISSUE THREAD

**Issue by icesnake2000** [libretro/slang-shaders#615]
Anyone knows why does this happen? Im running Majora's Mask on Mupen64core and I cant apply this shader. However I can apply it when I run Majora's Mask with Parallel64 core. The rest of vhs shaders can be applied though. Im on linux mint.

**Comment by hizzlekizzle** [comment]
Can you post a log of it failing to apply?

**Comment by icesnake2000** [comment]
Hi sorry for this late response. I have figured it out, and got it working. I just downloaded an old RA version and replaced the mudlord shaders. I guess I was too hasty and made this thread for nothing.

**Comment by hizzlekizzle** [comment]
no worries. I'm glad you got it worked out.
