### ISSUE TITLE
iOS cannot apply shader

### ISSUE THREAD

**Issue by DunhamGitHub** [libretro/slang-shaders#621]
Steps to reproduce:

1. Load .gbc title in mGBA core
2. Load shader for GBA

<img src="https://github.com/user-attachments/assets/bcc2e5c4-c03e-4842-862a-79ef6922356c" width="200px" />

**Comment by hizzlekizzle** [comment]
I'm able to load shaders just fine with mGBA core on iOS. Can you provide a log of your failure? Is this one of the shaders that comes with RetroArch or one you've added?

**Comment by DunhamGitHub** [comment]
I downloaded these: https://github.com/RetroCrisis/Retro-Crisis-GDV-NTSC

* I am going to close this since other shaders probably work

**Comment by hizzlekizzle** [comment]
yeah, if you downloaded shaders from elsewhere, you probably just didn't put them in the right location for the presets to work with the existing shader file locations.
