### ISSUE TITLE
pixel_aa_xform fails to load on Android

### ISSUE THREAD

**Issue by flavionm** [libretro/slang-shaders#657]
Running the current version on the Play Store (1.19.1) and with updated shaders, the pixel_aa_xform.slang shader fails to load. Some other shaders and presets also fail to load, with the same error as in the attached log.

[retroarch__2024_12_06__15_12_10.log](https://github.com/user-attachments/files/18042927/retroarch__2024_12_06__15_12_10.log)

The video driver being used is vulkan, and the phone is a Moto Edge 30 with Android 14,

**Comment by fishcu** [comment]
Hi @flavionm! I'm the dev of this shader preset.

My guess is that your installation of the shaders is broken. Please update the shaders using the online updater, and make sure to use presets from there, not from a manual installation.

I was not able to replicate your issue on my Android 13 phone. I also used Vulkan drivers for testing. I tried two different versions of RetroArch (Play Store version and latest nightly), and pixel_aa_xform worked on both versions here:

![image](https://github.com/user-attachments/assets/5cc90139-7fee-473e-9c6b-8c7cc90d6ee5)

![image](https://github.com/user-attachments/assets/1601ade9-8f22-4384-8215-b4d110554895)

Furthermore, please verify that you're using the latest version of the shader. When you view the shader parameters, you should see `=== Pixel AA v1.6 settings ===`, so `1.6` is the latest version.

**Comment by flavionm** [comment]
I used the build-in online updater, and checked if I was loading from the correct folder, and even tried changing it to a different one. Then I realized for some reason my Play Store install wasn't actually providing any version info, so now I'm not so sure it was actually the stable 1.19.1.

In the end I just went and installed the current nightly, and that fixed it.
