### ISSUE TITLE
Bad quality of handheld border images

### ISSUE THREAD

**Issue by mtmrc** [libretro/slang-shaders#661]
It seems like borders got converted to lower bit depth which creates banding and dithering issues, especially in the upper right corner of viewport which simulates external lighting. Borders in glsl shaders don't have this issue.

**Comment by hizzlekizzle** [comment]
Yes, it's from "optimizing" them. The glsl versions are ~3x the filesize, and we've had complaints from downstream projects that use our shaders about the size of the repo, which is mostly big png images.

**Comment by mtmrc** [comment]
I see. Well it's easy to "fix" by pointing the shader to old images, but wouldn't it be better to just delete that effect from viewport since it's so degraded, or are people just not bothered by that.

**Comment by hizzlekizzle** [comment]
Dunno. I guess nobody's noticed. They've been like that for 10 months 🤷 

There are some higher quality, higher resolution versions available on the libretro forums with and without the glare effect, if you're interested in replacing them locally.

**Comment by mtmrc** [comment]
Yeah, I already did. It seems it's more pronounced when a game has black backgrounds, so on a lot of games it's not as noticable. Anyway since it's done for file size reasons and majority doesn't seem to mind I guess it's not an issue.
