### ISSUE TITLE
Relative Path for ScaleFX

### ISSUE THREAD

**Issue by Papermanzero** [libretro/slang-shaders#80]
A port of the following glsl shader commit is missing for slang shaders.
https://github.com/libretro/glsl-shaders/commit/f92cb1a719d3cf3ff42e2213edc1d711180ae127

**Comment by Papermanzero** [comment]
Any update on that one?

**Comment by hizzlekizzle** [comment]
Should be all set now. I had to add a stock pass in front that can be replaced with whatever else (including multiple passes), it just needs the pass immediately preceding scalefx-pass0 to have an alias of 'refpass'. I think I got all of the presets updated, too, but let me know if I missed anything.
