### ISSUE TITLE
Game Gear handheld border shader has incorrect default parameters

### ISSUE THREAD

**Issue by nfp0** [libretro/slang-shaders#92]
This is what the Game Gear handheld border shader looks like on Vulkan on default parameters. The game image does not fill the border's screen. Adjusting the shader parameters fixes this, but they should have better defaults.

![retroarch screenshot 2018 11 04 - 12 42 47 14](https://user-images.githubusercontent.com/11202422/48030940-82051200-e14a-11e8-8ea0-d86c7e6176cb.png)

**Comment by hizzlekizzle** [comment]
I spotted the issue and it should be fixed now. Feel free to reopen the issue if it's not fixed.

**Comment by nfp0** [comment]
Thanks!
I think this is also present on the CG and GLSL shaders as well so they might need a similar fix.
