### ISSUE TITLE
Non-spec "//" comments in several presets

### ISSUE THREAD

**Issue by bearoso** [libretro/slang-shaders#95]
According to the Cg preset spec, which is inherited in slangp, the comment delimiter is "#" only. However, several presets use "//" by mistake:
```crt/crt-hyllian-multipass.slangp
reshade/bloom.slangp
reshade/blendoverlay.slangp
handheld/gb-palette-light.slangp
handheld/gb-palette-pocket.slangp
handheld/ds-hybrid-scalefx.slangp
handheld/ds-hybrid-sabr.slangp
```

I had a couple that were missing closing quotations but most were fixed. One remains:
`presets/tvout/tvout+snes-hires-blend.slangp`  with `scale0 = "1.0`

**Comment by hizzlekizzle** [comment]
Thanks for the heads-up.
I was/am excited to see slang/p support coming to snes9x! Which drivers will be using it?

**Comment by bearoso** [comment]
The GTK+/OpenGL work is pretty much done. It's basically a drop-in alongside glslp, so it's just a matter of figuring out how we're going to handle linking glslang on Windows for it to work on OpenGL there, too.
