### ISSUE TITLE
[Vulkan] Simpletex Has Transparent Black Bar on Right

### ISSUE THREAD

**Issue by Awakened0** [libretro/slang-shaders#99]
I found this issue when using any of the simpletex presets with mGBA and the Vulkan video driver:

![Castlevania - Aria of Sorrow (USA)-190418-183342](https://user-images.githubusercontent.com/4565863/56399123-2e7b1200-621a-11e9-9738-222b778646ea.png)

It doesn't happen when using the same slang version of the shader with the glcore driver. It also only shows up at wider aspect ratios, so you don't see it with GB or GBC unless you stretch them to something like 16:9:

![Super Mario Land 2 - 6 Golden Coins (USA, Europe)  DX by toruzz v1 8 1 -190418-183840](https://user-images.githubusercontent.com/4565863/56399165-7c901580-621a-11e9-85f2-dde6ed126e75.png)

**Comment by Awakened0** [comment]
Ahh wait, the 4k versions don't have the black bar under Vulkan. Maybe Vulkan isn't scaling the 2k background image the same way glcore does?

**Comment by hizzlekizzle** [comment]
ah, very possible. If you replace the background image with a black image, does it cover the whole screen?

**Comment by Awakened0** [comment]
Yeah, it does.

I found the [forum topic about the shader](https://forums.libretro.com/t/simple-textured-shader-for-non-backlit-lcd-systems-gbc-etc/15520) and I guess the black bar is expected behavior for non-square aspects at 1440p and up (which is why the 4k version was included). Still interesting to me that glcore acts differently.

**Comment by hizzlekizzle** [comment]
ok, glad to know it's expected behavior. but yeah, it's probably a bug in glcore, actually, similar to the way d3d11 stretches AR when you go fullscreen (or did... it might have been fixed recently)
